#!/bin/bash

# Go green to say openhd is starting
echo 0 >/sys/class/leds/openhd-x20dev\:red\:usr/brightness
echo 1 >/sys/class/leds/openhd-x20dev\:green\:usr/brightness
echo 0 >/sys/class/leds/openhd-x20dev\:blue\:usr/brightness

modprobe 88XXau_ohd rtw_amplifier_type_2g=0 rtw_amplifier_type_5g=1 rtw_RFE_type=1 rtw_TxBBSwing_2G=0 rtw_TxBBSwing_5G=3
modprobe HdZero

nice --10 openhd --air >& /external/OpenHDLog.txt

echo 0 >/sys/class/leds/openhd-x20dev\:red\:usr/brightness
echo 0 >/sys/class/leds/openhd-x20dev\:green\:usr/brightness
echo 1 >/sys/class/leds/openhd-x20dev\:blue\:usr/brightness

